# Generated by Django 3.2.5 on 2021-07-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('stock', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
