# Generated by Django 3.1.7 on 2021-03-06 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20210306_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='name',
            new_name='animal_id',
        ),
    ]
