# Generated by Django 3.2.5 on 2021-07-28 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
                ('name', models.CharField(max_length=100)),
                ('prefix', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
                ('name', models.CharField(max_length=100)),
                ('prefix', models.CharField(blank=True, max_length=5, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.city')),
            ],
            options={
                'db_table': 'districts',
                'ordering': ['name'],
            },
        ),
    ]
