# Generated by Django 3.2.5 on 2021-07-28 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tax_vkn_number', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_office', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal_name', models.CharField(max_length=255)),
                ('passport', models.CharField(max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('cat', 'Kedi'), ('dog', 'Dog'), ('exotic', 'Egzotik'), ('winged', 'Kanatlı'), ('tropical', 'Tropikal'), ('wild', 'Yabani'), ('other', 'Dİğer')], default='other', max_length=20)),
                ('spayed', models.BooleanField(blank=True, default=False, help_text='kısırlaştırılmış', null=True)),
                ('race', models.CharField(blank=True, help_text='ırk', max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('male', 'Erkek'), ('female', 'Dişi')], default='female', max_length=20)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'db_table': 'animals',
            },
        ),
    ]
