# Generated by Django 3.2.5 on 2021-07-28 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_color'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='common.city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='common.district'),
            preserve_default=False,
        ),
    ]
