# Generated by Django 3.2.5 on 2021-07-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210728_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='race',
        ),
        migrations.AddField(
            model_name='animal',
            name='specie',
            field=models.CharField(blank=True, help_text='ırk/tür', max_length=255, null=True),
        ),
    ]
