# Generated by Django 3.2.5 on 2021-07-28 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210728_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='animal_name',
            new_name='name',
        ),
    ]
