# Generated by Django 3.2.5 on 2021-07-28 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='animal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='customer.animal'),
            preserve_default=False,
        ),
    ]
