# Generated by Django 3.2.5 on 2021-07-28 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_appointment_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='customer.animal'),
        ),
    ]
